### ISSUE TITLE
Player: Anonymous sign in

### ISSUE THREAD

**Issue by NamrataAcharya02** [NamrataAcharya02/IRLAmongUs#100]
## User Story
As a **[Player]**, I would like **[anonymous sign in]**.

## Detailed Description
In homepage.js, add anonymous sign in functionality from Firebase when 'join a room' is clicked. 

## Tasks
- [ ] Add functions in homepage.js and connect to 'join a room'
- [ ] Be able to extract correct user.uid to uniquely identify each player

- [ ] Given **[Join a room]**, then **[allow anonymous sign in]**
