### ISSUE TITLE
Crewmate Epic

### ISSUE THREAD

**Issue by jlemoff** [NamrataAcharya02/IRLAmongUs#11]
## Epic
Describe the requirements of the epic.

## User Stories
- [ ] mark a task complete so I can contribute to my team.
- [ ] mark a task incomplete so I can undo an accidentally marked complete task.
- [ ] mark myself as dead so the player game count is updated if I am killed.
