### ISSUE TITLE
Player: join a lobby

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#12]
## User Story
As a **[player]**, I would like **[join a lobby]** so that **[I can play with other players]**.

## Detailed Description
In order for a user to join a lobby from the main landing page, they must tap the "join lobby" button and enter a code (distributed by the game admin.) Upon entering the code, a player should be prompted to enter their name then have the backend assign a role. After this has happened, the player should be directed to the main gameplay screen.

Note: tapping "join lobby" implies the user is a player of the game, opposed to being an admin.

## Tasks
- [x] #47
- [x] #48
- [x] #49
- [x] #57
- [x] #51
- [x] #50
- [x] write PlayerRoomController constructor -- using getRoom only, and createPlayer
- [x] Create a playerRoomControler object using player id
- [x] add room id to player object with playerRoomController
- [x] update the room object with player id  with playerRoomController

## Acceptance Criteria
- [x] Given **[a player has entered a valid room code into a text field]**, then **[the player is prompted to enter the name they wish to play with]**
- [x] Given **[a player has entered a name]**, then **[the player is redirected to a "lobby" where they await role and tasklist assignments and for the game to being]**
- [x] Given **[a player enters an invalid room code]**, then **[the user is prompted to enter a correct code]**
