### ISSUE TITLE
Player: view win screen

### ISSUE THREAD

**Issue by bluepaw59** [NamrataAcharya02/IRLAmongUs#121]
## User Story
As a **[Player]**, I would like **[view game end screen]** so that **[I know who won]**.

## Detailed Description
When game ends, a win screen should display

##Tasks
- [ ] Front end: make the game end screens
- [ ] Back end: hook up such that the game end screens render when called

## Acceptance Criteria
- [ ] Given **[Game end]**, then **[correct win screen displayed]**
