### ISSUE TITLE
Player: view a list of tasks

### ISSUE THREAD

**Issue by NamrataAcharya02** [NamrataAcharya02/IRLAmongUs#13]
## User Story
As a **[Player]**, I would like **[view a list of tasks]** so that **[I know what to do]**.

## Detailed Description
Both a crewmate and imposter would like to view a list of tasks for them to complete. The imposter's tasks will look the same as a crewmate's task list so that the imposter can blend in by doing tasks. However, the imposter's tasks will not affect the task completion bar.

## Tasks
- [ ] Given **[the inputted lists of tasks from the admin]**, then **[shuffle all the tasks]** 
- [ ] Given **[a shuffled list of tasks]**, then **[display the first 4 tasks of the shuffled tasks as the player task list]** 
- [x] Given **[completed tasks]**, then **[pop the completed task from the player list and display the next one on the shuffled list]** 
- [x] Given **[the player task list]**, then **[display it as an interactable checklist]**

## Acceptance Criteria
- [ ] Given **[I am in the game]**, then **[view a subset of tasks that I should be doing (or faking)]** 
- [ ] Given **[I am in the game]**, then **[a shuffled few tasks are presented to me]**
