### ISSUE TITLE
Player: receive gameplay role.

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#15]
## User Story
As a **[Player]**, I would like **[receive gameplay role]** so that **[I can play the game]**.

## Detailed Description
Players needs to know wether they are a crewmate or imposter to complete their roles in the game. As an imposter they will want to kill as many players as they can without being caught. As a crewmate they will want to finish all their tasks or figure out who the imposters are.

## Tasks
- [ ] generate a list of imposters and a list of crewmates using room fields
- [ ] add bridge between room and player that updates player roles

## Acceptance Criteria
- [ ] Given **[I am waiting in a lobby for the game to start]**, then **[receive a gameplay role when the Admin has started the game]**
- [ ] Given **[I push an accessible button for role viewing]**, then **[display my affiliation]**
