### ISSUE TITLE
Player: mark a task complete

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#18]
## User Story
As a **[player]**, I would like **[mark a task complete]** so that **[I can contribute to my team]**.

## Detailed Description
Completing tasks is essential to making game progress. Each **Player** receives a list randomized from the **Admin**s gameplay list. The goal for **Player** is to complete all the tasks they were issued. When all players complete all their tasks and an **Imposter** is still alive, the game is declared won.

Marking a task complete updates individual player status, therefore updating the entire games progress status.

## Tasks
- [ ] Marking a task as complete opens a pop up to prompt for certainty
- [ ] when pop-up confirmed, update the backend
- [ ] Add logic for this in PlayerGameController.js
- [x] remove completed task from player view
- [x] add a new task to player view

## Acceptance Criteria B
- [ ] Given **[a task has been complete]**, then **[a pop up for confirmation will be shown]**
- [ ] Given **[confirmation of task]**, then **[update/push changes to backend]**
- [ ] Given **[a mistake was made]**, then **[undo completion]**.
- [ ] (Given **[a pushed change]**, then **[update Player UI (remove completed, add new)]**. more below)
- [x] Given **[A submitted change]**, then **[remove completed task from UI]**.
- [x] Given **[A submitted change]**, then **[add a new task to the UI]**.

**Comment by richardkhillah** [comment]
If we use Acceptance Criteria A, then for completing a task, we can reuse the Voting mechanism. The difference will be the list that is shown and the text on the submit button.

If we use Acceptance Criteria B, then we code a timer that manages the submission of completed tasks.
