### ISSUE TITLE
Player: view task completion bar

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#20]
## User Story
As a **[player]**, I would like **[to view task bar]** so that **[I can see how many tasks I have remaining]**.

## Detailed Description
Completing tasks is an essential part of gameplay, and as a Player, especially a Crewmate, it is helpful to know how how many tasks I have remaining. The task completion bar indicates how many tasks have been completed, the number of incomplete tasks, and a visual progress bar indicating the number of completed tasks to total tasks.

## Tasks
- [ ] Given **[an in-progress game]**, then **[show a progress bar toward the top of the player screen]**
- [ ] Given **[a tasklist]**, then **[count number of completed tasks and total tasks]**.
- [x] Given **[tasklist counts]**, then **[display the total number of tasks remaining]**.
- [x] Given **[tasklist counts]**, then **[display the total number of completed tasks]**.
- [x] Given **[tasklist counts]**, then **[display a horizontal "progress bar" that shows completed tasks to total tasks]**.
- [ ] Given **[a task has been completed]**, then **[update the task completion bar]** .

##Acceptance Criteria
- [ ] Given **[a game is in session]**, then **[show a live task progress bar at the top of a player screen]**
- [ ] Given **[task has been completed]**, then **[have a live update to the progress bar]**
