### ISSUE TITLE
Player: receive emergency meeting notification

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#22]
## User Story
As a **[player]**, I would like **[receive emergency meeting notification]** so that **[I can participate in emergency meetings]**.

## Detailed Description
All players should receive a notification so they know when to gather for an emergency meeting. Players should not be late to discussions. Also, players should not be able to complete tasks when everyone else is in the meeting.

Note: 
Original Story:
As a player, I would like to know when to gather for an emergency meeting so I am not late to a discussion and am not continuing to do tasks when I should be with everyone else.

##Tasks
- [ ] Make a emergency screen
- [ ] have emergency screen open when meeting called
- [ ] Pause task updates

## Acceptance Criteria
- [ ] Given **[player calls meeting]**, then **[all players prompted to join meeting]**
- [ ] Given **[emergency meeting is called or in progress]**, then **[players do not have ability to mark tasks as complete]**
