### ISSUE TITLE
Player: set my name

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#24]
## User Story
As a **[player]**, I would like **[to change my name]** so that **[other players know who I am when voting]**.

## Detailed Description
Players need the ability to name themselves so players know who is who during gameplay, especially during voting. A player will be prompted to name themselves once they join a lobby, and will also have the option to change their name at any time with the "name" button.

## Tasks
- [ ] Create Player object that handles according to **Player** class diagram
- [ ] update the player object and associated db entry
- [ ] propagate changes to room instances
- [ ] create a name button and corresponding text field (or popup for UI purposes - easy cancellation, forces player to press submit to update their name in the DB)
- [ ] create a submit or accept button that triggers db change

## Acceptance Criteria
- [ ] Given **[a "name" button is tapped]**, then **[the player is prompted to change their name]**
- [ ]  Given **["player enters new name]**, then **[the players name is simultaneously updated for all instances of the game]**
