### ISSUE TITLE
Admin: add tasks to a list

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#26]
## User Story
As an **[Admin]**, I would like **[add tasks to a list]** so that **[I can customize tasks for my environment]**.

## Detailed Description
Once the system has task list, Admin can create a task and add it to the list at anytime during or before the game starts. Admin will give the detail description of the task and backend will generate task id for it.  

## Tasks
- [x] Given **[a button says "Add a task"]**, then **[be prompted to add name and description of the task]**
- [x] Given **[the interface displays]**, then **[type in name and description of the task]**
- [x] make a save list button 
- [x] hook save list button to back end such that when it is pressed, all the tasks are added or updated in the database

##Acceptance Criteria
- [x] Given **[a button says "Add Task"]**, then **[a new task input area is shown to edit tasks]**
- [x] Given **[a save list button]**, then **[all tasks get saved]**
