### ISSUE TITLE
Admin: create a lobby

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#31]
## User Story
As a **[admin]**, I would like **[create a lobby]** so that **[players can join my room to play]**.

## Detailed Description
Provide additional details and context.

## Tasks
- [x] #41
- [x] #42
- [x] #43
- [ ] Given **[unsuccessful login]**, then **[handle error]**
- [ ] Given **[closed login before auth]**, then **[handle error]**
- [x] #44
- [x] #45
- [x] #46

## Acceptance Criteria
- [x] Given **[a users wishes to play a game]**, then **[user can see two options to start a room and join a room]**.
- [ ] Given **[a user has tapped a button that create room]**, then **[they are assigned the role "Admin"]**
- [ ] Given **[a user is assigned a role as Admin]**, then **[they are presented with a page that enables them to modify/create a task list, set a number of imposters, and set a number of tasks each player should complete]**.
- [ ] Given **[an Admin has set all room parameters and tapped a start room button]**, then **[a room code is displayed on their screen for players to use for their entry code]**
