### ISSUE TITLE
Admin: view all players

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#35]
## User Story
As a **[admin]**, I would like **[to view all players]** so that **[I know who’s in the game]**.

## Detailed Description
When an admin creates a room, players will join the room. The admin needs the capability to see who joins the room. The admin can check who joined the room and who has not by checking the player names.

## Tasks
- [ ] Player object creation
- [ ] Player list in room
- [x] Display player list in front end
- [x] Create AdminWaiting.js file to handle displaying players who have joined
- [ ] Create AdminGame.js to display game screen for admin
- [ ] Add 'start game' button to notify all players and redirect them to the game screen (PlayerGame.js). Redirect admin to AdminGame.js to show game progress

## Acceptance Criteria
- [ ] Given **[a room (with players)]**, then **[view list of the names of the players in the room]**
