### ISSUE TITLE
Admin: set a number of imposters

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#39]
## User Story
As a **[admin]**, I would like **[to set a number of imposters]** so that **[I can balance the teams so there aren’t too many imposters or too many crewmates]**.

## Detailed Description
The admin should be able to set the number of imposters they want in their game to balance the game. Based on how many people are playing, there could be more than one imposter.

## Tasks
- [x] Create a number slider
- [x] Validate user input on frontend
- [x] (Create a recommender for number of imposters based on number of players in room - possibly not included)
- [x] update room with validated number of imposters from front end

## Acceptance Criteria
- [x] Given **[a textbox for numerical input]**, then **[input and set the number of imposters]**
- [x] Given **[the total number of players]**, then **[calculate a recommended amount of imposters as the default]**
- [x] (Given **[the user inputs a number less than or equal to the recommended number of imposters]**, then **[set the number of imposters based on user input]**)
- [x] (Given **[the user inputs a number greater than the recommended number of imposters]**, then **[reject user's input and ask for a new number]**)
