### ISSUE TITLE
User: control gameplay

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#71]
## Description
The bug is a flaw in project layout and decoupling. The application uses an MVC pattern, yet there is no ControllerObject that interacts with the Models and Views. The current paradigm moving forward would require coupling models with control, which defeats the MVC pattern.

## Steps to Reproduce
No steps.

## Expected Behavior
Frontend interacts with a Controller object, which interfaces with the database/model.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## User Story
As a **[user]**, I would like **[to control game progress depending on my gameplay role]** so that **[the game can run]**.

## Detailed Description
Provide additional details and context.

## Tasks
- [ ] Create RoomController parent class scaffold
- [ ] Create AdminRoomController subclass scaffold
- [ ] Create PlayerRoomController subclass scaffold
- [ ] (Needs acceptance) Create Crewmate/ImposterPlayerRoomController subclass scaffold
- [ ] Hookup AdminRoomController with Room and Admin objects
- [ ] Hookup PlayerRoomController with Room and Player objects
- [ ] Hookup any subclasses that may be needed
- [ ] Create conditional methods (e.g., vote () { if (room.status == Status.Emergency) { vote logic } }
- [ ] make model objects private. 

## Acceptance Criteria
- [ ] Given **[a user activates a story]**, then **[all functionality described in that story executes as defined.]**

## Relevant screenshots
None

[UML Class Diagram](//www.plantuml.com/plantuml/png/fLHDZnit3BtxLn2-r0lO1jhU1ZqaI8jY3ziid6qlGGwqHDkgzM58b1FtuxzNb6PtR8-BTf631zOZdqW-adgJ62DdPoUh4Doxu3a6Qod23tyj5l1ME-Cl3JVz7YsUA5uvJfJ5bE3A_yy9m28MhAiMEUL4iODVorTE2grTezftiCbUiGbUq4EDa3hus69z4j07DXj3iQ0hGiKhqbc9JOp7O3HKZzFihW1G0TJwbvurE-SC7h-7Ld8ZVPmPFGUFZku-mPRuhM9pf9P3EhjNiduWOkEt3Vt0iVo7ew7Fgs2fW7zF9ZumWQKDGzXS2TDrKz5XMhXFEvD0XMmrh0aGKZvGh68AhSK6zBgrPxbSGY7T0pef5np6Q4W31s2vo6Z2EQmpW-5lKk5LfB0cvAj0r7UgNNUhNIY6ITySbIqoFHZ_W5_ktI4ahaf01xFYDGU7N-vwrwm6roTC-_GKtWLtiCHqWw0B70lIgokgDOKNc9BP-ajOD4x4FwEZHupbMzCePGa3PAghhJM3l1uErVPR65grfVxu6CCsKaelf9jUAqhPSk-qCHwj-ODkcFP6xTzdRcdFsW3Vw-UhBuP5coJsfhrkmt8nA-FMoC2WeEE9EQ7VamRZELnl7oQGAHjw_t_2_4kDBu7JJY9tKWXykwnrGyWCl2DePLVJTqjGE_HRgWPv0gGLdDEychzVWgPKefv08-CQ4u7nnSChajn-SXItvDMfrlIg0ixa7h9snBkW1zLKySP3UXPkUjR-wQkYZPevxb0aZwxjg3mGSzdctXg9S_I040aL5x2ic2VFesrjStLhNGVDvNVvdbd28mt7qRFbCEu_aDtyIAW7H9PtsDn6JB8ET3dNiYCccRKbOQJnepVEkcdMRldwKVxFGACC9UPxRqyonPy1vJKoBZkvOXDo1EDLNpYmCCxYlI6lixF_0000)

![Image](https://github.com/NamrataAcharya02/IRLAmongUs/assets/25072000/b860e602-dd59-4e2a-be13-31d28c92b6b0)
