### ISSUE TITLE
[BUG] - room object does not save task list to databse

### ISSUE THREAD

**Issue by richardkhillah** [NamrataAcharya02/IRLAmongUs#86]
## Description
Give a clear and concise description of what the bug is.

## Steps to Reproduce
Steps to reproduce the bug:
- [ ] create a room object with a specified tasklist array
- [ ] attempt to get that object from the database
- [ ] attempt to call room.getTaskList()

## Expected Behavior
Tasklist object is saved to database (using the converter), and tasklist obejct is retrieved from the database.

## Additional Context
none

## Relevant screenshots
none.
